# Generated by Django 3.2 on 2021-04-16 15:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
        migrations.AlterModelOptions(
            name='sms',
            options={'verbose_name': 'SMS List', 'verbose_name_plural': 'SMS Lists'},
        ),
    ]
