# Generated by Django 3.2 on 2021-04-16 15:56

import django.core.validators
from django.db import migrations, models
import django.utils.timezone
import re


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_alter_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='sms',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Contact name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(help_text='e.g. 06xxxxxxxx', max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^-?\\d+\\Z'), code='invalid', message='Enter a valid integer.')], verbose_name='Phone number'),
        ),
    ]
