# Generated by Django 3.2 on 2021-04-29 02:11

import accounts.validators
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_auto_20210416_1556'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sms',
            options={'verbose_name': 'SMS', 'verbose_name_plural': 'SMS List'},
        ),
        migrations.AddField(
            model_name='sms',
            name='alias',
            field=models.CharField(blank=True, help_text='alpha-numériques (a-zA-Z)', max_length=11, null=True, verbose_name='Alias'),
        ),
        migrations.AddField(
            model_name='sms',
            name='attachement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Attachement (URL)'),
        ),
        migrations.AddField(
            model_name='sms',
            name='title',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(help_text='e.g. 06xxxxxxxx', max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^-?\\d+\\Z'), code='invalid', message='Enter a valid integer.'), accounts.validators.moroccan_phone], verbose_name='Phone number'),
        ),
        migrations.AlterField(
            model_name='sms',
            name='message',
            field=models.TextField(help_text='maximum characters: 459', max_length=450, verbose_name='Message'),
        ),
    ]
