# Generated by Django 3.2 on 2021-04-29 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sms', '0005_auto_20210429_0211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='user',
        ),
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='accounts.myuser'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sms',
            name='alias',
            field=models.CharField(blank=True, help_text='alpha-numériques (a-z,A-Z,0-9)', max_length=11, null=True, verbose_name='Alias'),
        ),
    ]
