# Generated by Django 3.2 on 2021-05-17 20:38

from django.db import migrations, models
import sms.models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0007_contact_send_sms'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=32)),
                ('file', models.FileField(blank=True, null=True, upload_to=sms.models.get_temp_path, verbose_name='CSV file')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('contacts', models.ManyToManyField(blank=True, null=True, related_name='contact_lists', to='sms.Contact')),
            ],
            options={
                'verbose_name': 'Contact List',
                'verbose_name_plural': 'Contact Lists',
            },
        ),
    ]
