# Generated by Django 3.2 on 2021-05-17 20:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sms', '0008_contactlist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactlist',
            options={'ordering': ('-created',), 'verbose_name': 'Contact List', 'verbose_name_plural': 'Contact Lists'},
        ),
        migrations.AddField(
            model_name='contactlist',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='contact_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contactlist',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='contact_lists', to='sms.Contact'),
        ),
    ]
