# Generated by Django 3.2 on 2021-05-17 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0009_auto_20210517_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactlist',
            name='list_name',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
