# Generated by Django 3.2 on 2021-05-17 23:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware
import sms.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sms', '0010_alter_contactlist_list_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactlist',
            name='created_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contactlist',
            name='updated_by',
            field=django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contactlist',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='contact_lists', to='sms.Contact', verbose_name='Select more Contacts'),
        ),
        migrations.AlterField(
            model_name='contactlist',
            name='file',
            field=models.FileField(blank=True, help_text='Upload Contacts from a CSV file', null=True, upload_to=sms.models.get_temp_path, verbose_name='CSV file'),
        ),
        migrations.AlterField(
            model_name='contactlist',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='contact_lists', to=settings.AUTH_USER_MODEL, verbose_name='Select from Users Contacts'),
        ),
    ]
