# Generated by Django 3.2 on 2021-05-18 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0012_alter_contactlist_created_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactlist',
            options={'ordering': ('-created',), 'verbose_name': 'List', 'verbose_name_plural': 'Lists'},
        ),
    ]
