# Generated by Django 3.2 on 2021-05-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_manager', '0003_alter_campaign_contact_lists'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='title',
            field=models.CharField(max_length=256, unique=True, verbose_name='Campaign name'),
        ),
    ]
