# Generated by Django 3.2 on 2021-05-21 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0013_alter_contactlist_options'),
        ('bulk_manager', '0004_alter_campaign_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='messages',
            field=models.ManyToManyField(blank=True, help_text='Select SMS messages to send.', to='sms.SMS', verbose_name='Select SMS'),
        ),
    ]
