# Generated by Django 3.2 on 2021-05-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulk_manager', '0005_campaign_messages'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='status',
            field=models.IntegerField(choices=[(2, 'Ready'), (0, 'Sending'), (1, 'Completed')], default=2),
        ),
    ]
