# Generated by Django 3.2 on 2021-04-16 03:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210416_0156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=150, verbose_name='Username'),
            preserve_default=False,
        ),
    ]
