# Generated by Django 3.2 on 2021-04-16 14:22

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_myuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'A user with that email address already exists.'}, max_length=256, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(help_text='e.g. 0655555555', max_length=10, validators=[accounts.validators.moroccan_phone]),
        ),
    ]
