# Generated by Django 3.2 on 2021-04-29 02:48

import accounts.validators
import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210416_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='phone',
            field=models.CharField(help_text='e.g. 06xxxxxxxx', max_length=10, validators=[django.core.validators.RegexValidator(re.compile('^-?\\d+\\Z'), code='invalid', message='Enter a valid integer.'), accounts.validators.moroccan_phone]),
        ),
    ]
